//! Phase 2: concrete command classifier backed by the single generated manifest.
//!
//! Loads `docs/rpc-sdk/command-classification-manifest.json` (embedded at build
//! time) so the Rust scheduler and the TS divergence-assertion layer consume the
//! SAME source of truth. Unknown commands fail closed — they are never assigned a
//! default lane. This preserves the `rpc-mode.ts:83-169` fast-lane/ordered split.

use std::collections::HashMap;

use serde::Deserialize;

use crate::scheduler::{CommandClassifier, Lane};

/// The generated manifest, embedded so the classifier is self-contained and
/// unit-testable without filesystem access. Regenerated by
/// `scripts/rpc-sdk/generate-command-manifest.ts` (CI `--check` guards drift).
const MANIFEST_JSON: &str =
	include_str!("../../../docs/rpc-sdk/command-classification-manifest.json");

#[derive(Debug, Deserialize)]
struct ManifestEntry {
	command: String,
	#[serde(rename = "bridgeScope")]
	_bridge_scope: String,
	lane: ManifestLane,
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum ManifestLane {
	FastLaneCancellation,
	FastLaneSafeRead,
	Ordered,
}

impl From<ManifestLane> for Lane {
	fn from(value: ManifestLane) -> Self {
		match value {
			ManifestLane::FastLaneCancellation => Self::FastLaneCancellation,
			ManifestLane::FastLaneSafeRead => Self::FastLaneSafeRead,
			ManifestLane::Ordered => Self::Ordered,
		}
	}
}

#[derive(Debug, Deserialize)]
struct Manifest {
	commands: Vec<ManifestEntry>,
}

/// Error returned when a command is not present in the generated manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownCommand(pub String);

impl std::fmt::Display for UnknownCommand {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(f, "unknown command not in generated manifest: {}", self.0)
	}
}

impl std::error::Error for UnknownCommand {}

/// Classifier backed by the embedded generated manifest.
#[derive(Debug, Clone)]
pub struct ManifestCommandClassifier {
	lanes: HashMap<String, Lane>,
}

impl ManifestCommandClassifier {
	/// Build from the embedded generated manifest. Panics only if the embedded
	/// artifact is malformed, which a passing build + the `--check` gate prevent.
	#[must_use]
	pub fn from_embedded() -> Self {
		let manifest: Manifest =
			serde_json::from_str(MANIFEST_JSON).expect("embedded command manifest must be valid JSON");
		let lanes = manifest
			.commands
			.into_iter()
			.map(|entry| (entry.command, Lane::from(entry.lane)))
			.collect();
		Self { lanes }
	}

	/// Number of classified commands (must equal the manifest commandCount).
	#[must_use]
	pub fn len(&self) -> usize {
		self.lanes.len()
	}

	/// Whether the classifier holds no commands (never true for a valid manifest).
	#[must_use]
	pub fn is_empty(&self) -> bool {
		self.lanes.is_empty()
	}
}

impl CommandClassifier for ManifestCommandClassifier {
	type Error = UnknownCommand;

	fn lane_for(&self, command: &str) -> Result<Lane, Self::Error> {
		self
			.lanes
			.get(command)
			.copied()
			.ok_or_else(|| UnknownCommand(command.to_string()))
	}
}

impl Default for ManifestCommandClassifier {
	fn default() -> Self {
		Self::from_embedded()
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn loads_full_manifest() {
		let c = ManifestCommandClassifier::from_embedded();
		// Phase 0 manifest enumerates 38 RpcCommand types.
		assert_eq!(c.len(), 38);
		assert!(!c.is_empty());
	}

	#[test]
	fn preserves_rpc_mode_lane_split() {
		let c = ManifestCommandClassifier::from_embedded();
		// Cancellations bypass the ordered chain.
		assert_eq!(c.lane_for("abort").unwrap(), Lane::FastLaneCancellation);
		assert_eq!(c.lane_for("abort_bash").unwrap(), Lane::FastLaneCancellation);
		assert_eq!(c.lane_for("abort_retry").unwrap(), Lane::FastLaneCancellation);
		// Pure snapshot reads bypass the ordered chain (incl. get_pending_workflow_gates).
		assert_eq!(c.lane_for("get_state").unwrap(), Lane::FastLaneSafeRead);
		assert_eq!(c.lane_for("get_pending_workflow_gates").unwrap(), Lane::FastLaneSafeRead);
		// Mutating commands stay ordered.
		assert_eq!(c.lane_for("prompt").unwrap(), Lane::Ordered);
		assert_eq!(c.lane_for("set_model").unwrap(), Lane::Ordered);
		assert_eq!(c.lane_for("bash").unwrap(), Lane::Ordered);
	}

	#[test]
	fn unknown_command_fails_closed() {
		let c = ManifestCommandClassifier::from_embedded();
		let err = c.lane_for("definitely_not_a_command").unwrap_err();
		assert_eq!(err, UnknownCommand("definitely_not_a_command".to_string()));
	}
}
