import { describe, expect, it } from "bun:test";
import { RalplanIrcCoordinator } from "@gajae-code/coding-agent/gjc-runtime/ralplan-irc-coordinator";
import { AgentRegistry } from "@gajae-code/coding-agent/registry/agent-registry";
import type { AgentSession } from "@gajae-code/coding-agent/session/agent-session";

function setup(timeout = 60_000) { const registry = new AgentRegistry(); const coordinator = new RalplanIrcCoordinator({ registry, cwd: "/tmp", passTimeoutMs: timeout }); coordinator.startPass({ parentSessionId: "p", runId: "r", stageN: 1, cursorGeneration: 1 }); return { registry, coordinator }; }
function peer(h: ReturnType<typeof setup>, id: string, role: "planner" | "architect" | "critic", attach = true) { const registration = h.registry.register({ id, displayName: role, kind: "sub", session: null }); h.coordinator.bindRegisteredChild(id, { parentSessionId: "p", runId: "r", role, token: registration.token }); if (attach) h.registry.attachSession(id, {} as AgentSession, undefined, { token: registration.token }); return registration; }

describe("Ralplan IRC three-peer gate", () => {
 it("pre-registered running agent with null session does not satisfy attachment gate", () => { const h = setup(); peer(h, "planner", "planner", false); peer(h, "architect", "architect"); peer(h, "critic", "critic"); expect(h.coordinator.state).toBe("awaiting_attachments"); });
 it("all three matching attached sessions advance to required DM gate", () => { const h = setup(); peer(h, "planner", "planner"); peer(h, "architect", "architect"); peer(h, "critic", "critic"); expect(h.coordinator.state).toBe("awaiting_required_dm"); });
 it("delayed Critic model startup still delivers mandatory DM before Planner hold release", () => { const h = setup(); peer(h, "planner", "planner"); peer(h, "architect", "architect"); const critic = peer(h, "critic", "critic", false); expect(h.coordinator.state).toBe("awaiting_attachments"); h.registry.attachSession("critic", {} as AgentSession, undefined, { token: critic.token }); expect(h.coordinator.state).toBe("awaiting_required_dm"); h.coordinator.recordDelivery({ from: "critic", to: "planner", body: "review", delivered: true }); expect(h.coordinator.state).toBe("deliberation_open"); });
 it("Planner and reviewer finalization remain blocked until Critic to Planner delivery is recorded", () => { const h = setup(); peer(h, "planner", "planner"); peer(h, "architect", "architect"); peer(h, "critic", "critic"); h.coordinator.recordDelivery({ from: "architect", to: "planner", body: "other", delivered: true }); expect(h.coordinator.state).toBe("awaiting_required_dm"); });
 it("successful Critic to Planner delivery releases held role prompts deterministically", () => { const h = setup(); peer(h, "planner", "planner"); peer(h, "architect", "architect"); peer(h, "critic", "critic"); h.coordinator.recordDelivery({ from: "critic", to: "planner", body: "required", delivered: true }); expect(h.coordinator.state).toBe("deliberation_open"); expect(h.coordinator.transcript).toEqual([]); });
 it("timer writer failure leaves the pass retryable instead of swallowing degradation", async () => { const h = setup(5); peer(h, "planner", "planner"); peer(h, "architect", "architect"); peer(h, "critic", "critic"); await Bun.sleep(20); expect(h.coordinator.state).toBe("awaiting_required_dm"); expect(h.coordinator.diagnostics).toHaveLength(1); });
});
