/**
 * Streaming edit abort tests.
 */

import { afterEach, beforeEach, expect, it, vi } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { Agent, type AgentTool } from "@gajae-code/agent-core";
import { type AssistantMessage, getBundledModel, type StopReason, type ToolCall } from "@gajae-code/ai";
import { AssistantMessageEventStream } from "@gajae-code/ai/utils/event-stream";
import { Snowflake } from "@gajae-code/utils";
import * as z from "zod/v4";
import { ModelRegistry } from "../src/config/model-registry";
import { Settings } from "../src/config/settings";
import { AgentSession } from "../src/session/agent-session";
import { AuthStorage } from "../src/session/auth-storage";
import { SessionManager } from "../src/session/session-manager";
import * as autoGeneratedGuard from "../src/tools/auto-generated-guard";
import { ToolError } from "../src/tools/tool-errors";

function createAssistantMessage(content: AssistantMessage["content"], stopReason: StopReason): AssistantMessage {
	return {
		role: "assistant",
		content,
		api: "anthropic-messages",
		provider: "anthropic",
		model: "mock",
		usage: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
			totalTokens: 0,
			cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
		},
		stopReason,
		timestamp: Date.now(),
	};
}

function createToolCall(id: string, args: Record<string, unknown>): ToolCall {
	return {
		type: "toolCall",
		id,
		name: "edit",
		arguments: args,
	};
}

function lastAssistantMessage(messages: Array<{ role: string }>): AssistantMessage | undefined {
	for (let i = messages.length - 1; i >= 0; i--) {
		const msg = messages[i];
		if (msg.role === "assistant") return msg as AssistantMessage;
	}
	return undefined;
}

function createRng(seed: number): () => number {
	let state = seed % 2147483647;
	if (state <= 0) state += 2147483646;
	return () => {
		state = (state * 48271) % 2147483647;
		return state / 2147483647;
	};
}

function chunkStringRandomly(text: string, seed: number): string[] {
	const rand = createRng(seed);
	const chunks: string[] = [];
	let offset = 0;
	while (offset < text.length) {
		const remaining = text.length - offset;
		const maxSize = Math.min(8, remaining);
		const size = Math.max(1, Math.floor(rand() * maxSize) + 1);
		chunks.push(text.slice(offset, offset + size));
		offset += size;
	}
	return chunks;
}

async function createSession(
	tempDir: string,
	streamFn: Agent["streamFn"],
	tool: AgentTool,
	obfuscator?: { deobfuscate(text: string): string; deobfuscateObject<T>(value: T): T; hasSecrets(): boolean },
): Promise<{ agent: Agent; session: AgentSession; authStorage: AuthStorage }> {
	const model = getBundledModel("anthropic", "claude-sonnet-4-5")!;
	const agent = new Agent({
		getApiKey: () => "test-key",
		initialState: {
			model,
			systemPrompt: ["Test"],
			tools: [tool],
		},
		streamFn,
	});

	const sessionManager = SessionManager.inMemory(tempDir);
	const settings = Settings.isolated({ "edit.streamingAbort": true });
	const authStorage = await AuthStorage.create(path.join(tempDir, "testauth.db"));
	authStorage.setRuntimeApiKey("anthropic", "test-key");
	const modelRegistry = new ModelRegistry(authStorage, path.join(tempDir, "models.yml"));

	return {
		agent,
		session: new AgentSession({
			agent,
			sessionManager,
			settings,
			modelRegistry,
			obfuscator: obfuscator as never,
		}),
		authStorage,
	};
}

function buildEditTool(): AgentTool {
	const schema = z.object({
		path: z.string(),
		diff: z.string(),
		op: z.string().optional(),
		rename: z.string().optional(),
	});

	return {
		name: "edit",
		label: "Edit",
		description: "",
		parameters: schema,
		async execute() {
			return { content: [{ type: "text", text: "ok" }] };
		},
	};
}

function createStreamForDiff(
	path: string,
	chunks: string[],
	abortSignalRef: { current?: AbortSignal },
	streamStateRef?: { deltaCount: number; waitBeforeFirstDelta?: Promise<void> },
): Agent["streamFn"] {
	let callIndex = 0;
	return (_model, _context, options) => {
		abortSignalRef.current = options?.signal;
		const stream = new AssistantMessageEventStream();
		const toolCallId = "call_edit_1";
		let diffSoFar = "";
		let aborted = false;

		const notifyAbort = () => {
			if (aborted) return;
			aborted = true;
			const partialCall = createToolCall(toolCallId, { path, diff: diffSoFar });
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: "",
				partial: createAssistantMessage([partialCall], "stop"),
			});
			stream.push({ type: "error", reason: "aborted", error: createAssistantMessage([], "aborted") });
		};

		options?.signal?.addEventListener("abort", notifyAbort, { once: true });

		queueMicrotask(async () => {
			if (callIndex > 0) {
				const finalMessage = createAssistantMessage([{ type: "text", text: "done" }], "stop");
				stream.push({ type: "done", reason: "stop", message: finalMessage });
				callIndex++;
				return;
			}
			const startMessage = createAssistantMessage([], "stop");
			stream.push({ type: "start", partial: startMessage });

			const startCall = createToolCall(toolCallId, { path, diff: "" });
			stream.push({ type: "toolcall_start", contentIndex: 0, partial: createAssistantMessage([startCall], "stop") });
			if (streamStateRef?.waitBeforeFirstDelta) {
				await streamStateRef.waitBeforeFirstDelta;
			}

			for (const chunk of chunks) {
				if (aborted) return;
				diffSoFar += chunk;
				if (streamStateRef) {
					streamStateRef.deltaCount += 1;
				}
				const partialCall = createToolCall(toolCallId, { path, diff: diffSoFar });
				stream.push({
					type: "toolcall_delta",
					contentIndex: 0,
					delta: chunk,
					partial: createAssistantMessage([partialCall], "stop"),
				});
				await Bun.sleep(0);
			}

			if (aborted) return;

			const finalCall = createToolCall(toolCallId, { path, diff: diffSoFar });
			const finalMessage = createAssistantMessage([finalCall], "toolUse");
			stream.push({ type: "toolcall_end", contentIndex: 0, toolCall: finalCall, partial: finalMessage });
			stream.push({ type: "done", reason: "toolUse", message: finalMessage });
			callIndex++;
		});

		return stream;
	};
}

function createStreamForToolCallArgs(
	name: string,
	id: string,
	argsByDelta: Record<string, unknown>[],
	abortSignalRef: { current?: AbortSignal },
): Agent["streamFn"] {
	let callIndex = 0;
	return (_model, _context, options) => {
		abortSignalRef.current = options?.signal;
		const stream = new AssistantMessageEventStream();
		let aborted = false;
		const currentArgs = () => argsByDelta.at(-1) ?? {};

		const notifyAbort = () => {
			if (aborted) return;
			aborted = true;
			const partialCall = { ...createToolCall(id, currentArgs()), name };
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: "",
				partial: createAssistantMessage([partialCall], "stop"),
			});
			stream.push({ type: "error", reason: "aborted", error: createAssistantMessage([], "aborted") });
		};

		options?.signal?.addEventListener("abort", notifyAbort, { once: true });

		queueMicrotask(() => {
			if (callIndex > 0) {
				stream.push({
					type: "done",
					reason: "stop",
					message: createAssistantMessage([{ type: "text", text: "done" }], "stop"),
				});
				callIndex++;
				return;
			}

			stream.push({ type: "start", partial: createAssistantMessage([], "stop") });
			const startCall = { ...createToolCall(id, {}), name };
			stream.push({ type: "toolcall_start", contentIndex: 0, partial: createAssistantMessage([startCall], "stop") });
			for (const args of argsByDelta) {
				if (aborted) return;
				const partialCall = { ...createToolCall(id, args), name };
				stream.push({
					type: "toolcall_delta",
					contentIndex: 0,
					delta: "x",
					partial: createAssistantMessage([partialCall], "stop"),
				});
			}
			if (aborted) return;

			const finalCall = { ...createToolCall(id, currentArgs()), name };
			const finalMessage = createAssistantMessage([finalCall], "toolUse");
			stream.push({ type: "toolcall_end", contentIndex: 0, toolCall: finalCall, partial: finalMessage });
			stream.push({ type: "done", reason: "toolUse", message: finalMessage });
			callIndex++;
		});

		return stream;
	};
}

let tempDir: string;
const editTool = buildEditTool();
const seeds = [7, 21, 42, 84, 128];

beforeEach(() => {
	tempDir = path.join(os.tmpdir(), `pi-streaming-edit-${Snowflake.next()}`);
	fs.mkdirSync(tempDir, { recursive: true });
});

afterEach(async () => {
	if (tempDir) {
		fs.rmSync(tempDir, { recursive: true, force: true });
	}
});

it("does not abort for successful patches across random streams", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-beta\n+beta2\n";

	for (const seed of seeds) {
		const chunks = chunkStringRandomly(diff, seed);
		const abortSignalRef: { current?: AbortSignal } = {};
		const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef);
		const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

		try {
			await session.prompt("apply patch");

			const lastAssistant = lastAssistantMessage(session.state.messages);
			expect(lastAssistant?.stopReason).not.toBe("aborted");
			expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		} finally {
			try {
				await session.dispose();
			} finally {
				authStorage.close();
			}
		}
	}
});

it("aborts for failing patches across random streams", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-omega\n+beta2\n";

	for (const seed of seeds) {
		const chunks = chunkStringRandomly(diff, seed);
		const abortSignalRef: { current?: AbortSignal } = {};
		const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef);
		const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

		try {
			await session.prompt("apply patch");

			const lastAssistant = lastAssistantMessage(session.state.messages);
			expect(lastAssistant?.stopReason).toBe("aborted");
			expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		} finally {
			try {
				await session.dispose();
			} finally {
				authStorage.close();
			}
		}
	}
});

it("does not abort when auto-generated peek fails with ENOENT (non-ToolError)", async () => {
	const checkSpy = vi
		.spyOn(autoGeneratedGuard, "assertEditableFile")
		.mockRejectedValue(Object.assign(new Error("ENOENT"), { code: "ENOENT" }));

	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-beta\n+beta2\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunkStringRandomly(diff, 7), abortSignalRef);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");

	try {
		await session.prompt("apply patch");

		expect(abortSpy).not.toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).not.toBe("aborted");
	} finally {
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts when auto-generated check rejects with ToolError", async () => {
	const checkSpy = vi
		.spyOn(autoGeneratedGuard, "assertEditableFile")
		.mockRejectedValue(new ToolError("Cannot modify auto-generated file"));

	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-beta\n+beta2\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunkStringRandomly(diff, 7), abortSignalRef);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");

	try {
		await session.prompt("apply patch");

		expect(abortSpy).toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).toBe("aborted");
	} finally {
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("resolves local:// internal-scheme paths through the protocol handler instead of panicking", async () => {
	// Plan-mode persists the plan file under the synthetic local:// URL scheme.
	// Earlier the streaming pre-cache (#preCacheStreamingEditFile →
	// #getStreamingEditToolCall) called resolveToCwd() unconditionally on the
	// path, which throws for internal-scheme URLs via assertNotInternalUrl().
	// The throw escaped the synchronous interceptor as an Unhandled Rejection
	// and killed the session.
	//
	// The fix routes `local://` paths through resolveLocalUrlToPath() so they
	// map onto the session's on-disk local-artifacts directory; pre-caching,
	// auto-generated detection, and post-edit invalidation all run on the real
	// file. Drive a streaming Edit toolcall with path: 'local://PLAN.md' and
	// confirm the session completes without panicking and that
	// assertEditableFile is invoked with a real (non-internal-scheme) absolute
	// path so the auto-generated guard works for plan-mode edits too.
	const checkSpy = vi.spyOn(autoGeneratedGuard, "assertEditableFile");
	const diff = "@@\n-old\n+new\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const chunks = chunkStringRandomly(diff, 7);
	const streamFn = createStreamForDiff("local://PLAN.md", chunks, abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("edit plan file");

		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant).toBeDefined();
		expect(lastAssistant?.stopReason).not.toBe("aborted");
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);

		// Confirm pre-cache resolved the URL rather than skipping it: the
		// auto-generated guard should have been invoked with a concrete fs path
		// (absolute, no internal scheme) plus the original local:// display path.
		expect(checkSpy).toHaveBeenCalled();
		const [absolutePath, displayPath] = checkSpy.mock.calls[0] ?? [];
		expect(typeof absolutePath).toBe("string");
		expect(absolutePath).toMatch(/^(?:\/|[A-Za-z]:[\\/])/);
		expect(absolutePath).not.toMatch(/^[a-z]+:\/\//);
		expect(displayPath).toBe("local://PLAN.md");
	} finally {
		checkSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts auto-generated file edits as soon as the path is available", async () => {
	const generatedPath = path.join(tempDir, "generated.ts");
	await Bun.write(generatedPath, "// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const diff = "@@\n-export const foo = 1;\n+export const foo = 2;\n";
	const chunks = chunkStringRandomly(diff, 7);
	const waitBeforeFirstDelta = Promise.withResolvers<void>();
	const streamState = { deltaCount: 0, waitBeforeFirstDelta: waitBeforeFirstDelta.promise };
	const streamFn = createStreamForDiff("generated.ts", chunks, abortSignalRef, streamState);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");
	const checkStarted = Promise.withResolvers<void>();
	const releaseCheck = Promise.withResolvers<void>();
	const checkSpy = vi.spyOn(autoGeneratedGuard, "assertEditableFile").mockImplementation(async () => {
		checkStarted.resolve();
		await releaseCheck.promise;
		throw new ToolError("Cannot modify auto-generated file");
	});

	try {
		const promptPromise = session.prompt("apply patch");
		await checkStarted.promise;

		expect(streamState.deltaCount).toBe(0);

		releaseCheck.resolve();
		waitBeforeFirstDelta.resolve();
		await promptPromise;

		expect(checkSpy).toHaveBeenCalledWith(generatedPath, "generated.ts");
		expect(abortSpy).toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).toBe("aborted");
	} finally {
		waitBeforeFirstDelta.resolve();
		releaseCheck.resolve();
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("processes append-only streaming diffs linearly and dedupes guard invocation", async () => {
	const lineCount = 40;
	const original = `${Array.from({ length: lineCount }, (_, index) => `line-${index}`).join("\n")}\n`;
	await Bun.write(path.join(tempDir, "sample.txt"), original);
	const chunks = ["@@\n"];
	for (let index = 0; index < lineCount; index++) {
		chunks.push(`-line-${index}\n`, `+line-${index}-new\n`);
	}
	const finalSize = chunks.join("").length;
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(session.streamingEditDebugCounters.guardRuns).toBe(chunks.length + 1);
		expect(session.streamingEditDebugCounters.processedChars).toBeLessThanOrEqual(finalSize + 1);
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(lineCount);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts when a bad removed line appears in the first completed suffix", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", ["@@\n", "-omega\n", "+beta2\n"], abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(1);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts when a bad removed line appears only in a later suffix", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", ["@@\n", "-alpha\n", "+alpha2\n", "-omega\n"], abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(2);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("falls back to a full check when a streaming diff mutates non-append", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForToolCallArgs(
		"edit",
		"call_edit_non_append",
		[
			{ path: "sample.txt", diff: "@@\n-alpha\n" },
			{ path: "sample.txt", diff: "@@\n-omega\n" },
		],
		abortSignalRef,
	);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(session.streamingEditDebugCounters.fullChecks).toBeGreaterThanOrEqual(1);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("uses full-diff fallback with obfuscator and preserves abort correctness", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "real-secret\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", ["@@\n", "-masked-secret\n"], abortSignalRef);
	const obfuscator = {
		hasSecrets: () => true,
		deobfuscate: (text: string) => text.replaceAll("masked-secret", "missing-secret"),
		deobfuscateObject: <T>(value: T) => value,
	};
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool, obfuscator);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(session.streamingEditDebugCounters.fullChecks).toBeGreaterThanOrEqual(1);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("caches non-update edit verdicts and skips later deltas", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForToolCallArgs(
		"edit",
		"call_edit_create",
		[
			{ path: "sample.txt", diff: "@@\n-alpha\n", op: "create" },
			{ path: "sample.txt", diff: "@@\n-omega\n", op: "create" },
		],
		abortSignalRef,
	);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(session.streamingEditDebugCounters.guardRuns).toBe(1);
		expect(session.streamingEditDebugCounters.processedChars).toBe(0);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});
it("G013 SEAM-ABORT catches a bad removed line completed exactly at the processed suffix seam", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", ["@@\n", "-omega", "\n+beta2\n"], abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(1);
		expect(session.streamingEditDebugCounters.processedChars).toBeLessThanOrEqual("@@\n-omega\n+beta2\n".length);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("G013 PARTIAL-LINE-DEFER waits for a bad removed line newline before aborting", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const releaseFinalChunk = Promise.withResolvers<void>();
	let afterPartial: { aborted: boolean; checkedRemovedLines: number } | undefined;
	const streamFn: Agent["streamFn"] = (_model, _context, options) => {
		abortSignalRef.current = options?.signal;
		const stream = new AssistantMessageEventStream();
		const toolCallId = "call_edit_partial_defer";
		let diffSoFar = "";
		let aborted = false;
		options?.signal?.addEventListener(
			"abort",
			() => {
				aborted = true;
				const partialCall = createToolCall(toolCallId, { path: "sample.txt", diff: diffSoFar });
				stream.push({
					type: "toolcall_delta",
					contentIndex: 0,
					delta: "",
					partial: createAssistantMessage([partialCall], "stop"),
				});
				stream.push({ type: "error", reason: "aborted", error: createAssistantMessage([], "aborted") });
			},
			{ once: true },
		);

		queueMicrotask(async () => {
			stream.push({ type: "start", partial: createAssistantMessage([], "stop") });
			stream.push({
				type: "toolcall_start",
				contentIndex: 0,
				partial: createAssistantMessage([createToolCall(toolCallId, { path: "sample.txt", diff: "" })], "stop"),
			});
			diffSoFar = "@@\n-omega";
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: diffSoFar,
				partial: createAssistantMessage(
					[createToolCall(toolCallId, { path: "sample.txt", diff: diffSoFar })],
					"stop",
				),
			});
			await Bun.sleep(0);
			afterPartial = {
				aborted: options?.signal?.aborted ?? false,
				checkedRemovedLines: 0,
			};
			await releaseFinalChunk.promise;
			if (aborted) return;
			diffSoFar += "\n";
			const finalCall = createToolCall(toolCallId, { path: "sample.txt", diff: diffSoFar });
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: "\n",
				partial: createAssistantMessage([finalCall], "stop"),
			});
			if (aborted) return;
			stream.push({
				type: "toolcall_end",
				contentIndex: 0,
				toolCall: finalCall,
				partial: createAssistantMessage([finalCall], "toolUse"),
			});
			stream.push({ type: "done", reason: "toolUse", message: createAssistantMessage([finalCall], "toolUse") });
		});
		return stream;
	};
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		const promptPromise = session.prompt("apply patch");
		while (!afterPartial) await Bun.sleep(0);
		expect(afterPartial).toEqual({ aborted: false, checkedRemovedLines: 0 });
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(0);

		releaseFinalChunk.resolve();
		await promptPromise;

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(1);
	} finally {
		releaseFinalChunk.resolve();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("G013 ABORT-MIDDLE catches a bad removed line in a middle suffix", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff(
		"sample.txt",
		["@@\n", "-alpha\n", "+alpha2\n", "-omega\n", "+omega2\n", "-gamma\n"],
		abortSignalRef,
	);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(2);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("G013 APPEND-ONLY-LINEAR handles 100 growing valid deltas without quadratic processing", async () => {
	const lineCount = 50;
	const original = `${Array.from({ length: lineCount }, (_, index) => `line-${index}`).join("\n")}\n`;
	await Bun.write(path.join(tempDir, "sample.txt"), original);
	const chunks = Array.from({ length: lineCount }, (_, index) => `-line-${index}\n+line-${index}-new\n`);
	const finalDiff = `@@\n${chunks.join("")}`;
	const deltas = Array.from({ length: 100 }, (_, index) =>
		finalDiff.slice(0, Math.ceil((finalDiff.length * (index + 1)) / 100)),
	);
	const argsByDelta = deltas.map(diff => ({ path: "sample.txt", diff }));
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForToolCallArgs("edit", "call_edit_linear_100", argsByDelta, abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).not.toBe("aborted");
		expect(session.streamingEditDebugCounters.guardRuns).toBe(101);
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(lineCount);
		expect(session.streamingEditDebugCounters.processedChars).toBeLessThanOrEqual(finalDiff.length + 1);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("G013 NON-EDIT-SKIP caches non-edit verdict and never aborts later bad-looking deltas", async () => {
	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForToolCallArgs(
		"bash",
		"call_non_edit_skip",
		[
			{ path: "sample.txt", diff: "@@\n-omega\n" },
			{ path: "sample.txt", diff: "@@\n-still-missing\n" },
		],
		abortSignalRef,
	);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("run command");

		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).not.toBe("aborted");
		expect(session.streamingEditDebugCounters.nonEditDeterminations).toBe(1);
		expect(session.streamingEditDebugCounters.guardRuns).toBe(0);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("G013 NO-FALSE-ABORT accepts a fully valid large edit", async () => {
	const lineCount = 200;
	const original = `${Array.from({ length: lineCount }, (_, index) => `valid-${index}`).join("\n")}\n`;
	await Bun.write(path.join(tempDir, "sample.txt"), original);
	const chunks = [
		"@@\n",
		...Array.from({ length: lineCount }, (_, index) => `-valid-${index}\n+valid-${index}-new\n`),
	];
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("apply patch");

		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		expect(lastAssistantMessage(session.state.messages)?.stopReason).not.toBe("aborted");
		expect(session.streamingEditDebugCounters.checkedRemovedLines).toBe(lineCount);
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});
