// Generated by scripts/rpc-sdk/generate-rpc-sdk-types.ts. Do not edit by hand.

export const PROTOCOL_VERSION = 1 as const;
export const INVENTORY_SCHEMA_VERSION = 1 as const;
export const INVENTORY_KIND = "rpc-sdk-runtime-io-inventory" as const;
export const INVENTORY_TOTAL_ITEMS = 90 as const;

export const COMMANDS = [
	"abort",
	"abort_and_prompt",
	"abort_bash",
	"abort_retry",
	"bash",
	"branch",
	"compact",
	"cycle_model",
	"cycle_thinking_level",
	"export_html",
	"follow_up",
	"get_available_models",
	"get_branch_messages",
	"get_last_assistant_text",
	"get_login_providers",
	"get_messages",
	"get_pending_workflow_gates",
	"get_session_stats",
	"get_state",
	"handoff",
	"login",
	"negotiate_unattended",
	"new_session",
	"prompt",
	"set_auto_compaction",
	"set_auto_retry",
	"set_follow_up_mode",
	"set_host_tools",
	"set_host_uri_schemes",
	"set_interrupt_mode",
	"set_model",
	"set_session_name",
	"set_steering_mode",
	"set_thinking_level",
	"set_todos",
	"steer",
	"switch_session",
	"workflow_gate_response",
] as const;
export type Command = (typeof COMMANDS)[number];

export const AGENT_EVENTS = [
	"agent_end",
	"agent_start",
	"auto_compaction_end",
	"auto_compaction_start",
	"auto_retry_end",
	"auto_retry_start",
	"goal_updated",
	"irc_message",
	"message_end",
	"message_start",
	"message_update",
	"notice",
	"retry_fallback_applied",
	"retry_fallback_succeeded",
	"subagent_steer_message",
	"thinking_level_changed",
	"todo_auto_clear",
	"todo_reminder",
	"tool_execution_end",
	"tool_execution_start",
	"tool_execution_update",
	"ttsr_triggered",
	"turn_end",
	"turn_start",
] as const;
export type AgentEvent = (typeof AGENT_EVENTS)[number];

export const FRAME_TYPES = [
	"error",
	"event",
	"host_tool_call",
	"host_uri_request",
	"permission_request",
	"ready",
	"reset",
	"response",
	"ui_request",
	"workflow_gate",
] as const;
export type InventoryFrameType = (typeof FRAME_TYPES)[number];

export const NOTIFICATION_SERVER_MESSAGES = [
	"action_needed",
	"action_resolved",
	"activity",
	"config_update",
	"context_update",
	"file_attachment",
	"hello",
	"identity_header",
	"image_attachment",
	"inbound_ack",
	"pong",
	"reply_rejected",
	"turn_stream",
] as const;
export type NotificationServerMessage = (typeof NOTIFICATION_SERVER_MESSAGES)[number];

export const NOTIFICATION_CLIENT_MESSAGES = [
	"config_command",
	"hello",
	"ping",
	"reply",
	"user_message",
] as const;
export type NotificationClientMessage = (typeof NOTIFICATION_CLIENT_MESSAGES)[number];

export const SCHEDULING_LANES = [
	"fast_lane_cancellation",
	"fast_lane_safe_read",
	"ordered",
] as const;
export type SchedulingLane = (typeof SCHEDULING_LANES)[number];

export const COMMAND_CLASSIFICATION = {
	"abort": { lane: "fast_lane_cancellation", bridgeScope: "prompt" },
	"abort_and_prompt": { lane: "ordered", bridgeScope: "prompt" },
	"abort_bash": { lane: "fast_lane_cancellation", bridgeScope: "bash" },
	"abort_retry": { lane: "fast_lane_cancellation", bridgeScope: "control" },
	"bash": { lane: "ordered", bridgeScope: "bash" },
	"branch": { lane: "ordered", bridgeScope: "session" },
	"compact": { lane: "ordered", bridgeScope: "control" },
	"cycle_model": { lane: "ordered", bridgeScope: "model" },
	"cycle_thinking_level": { lane: "ordered", bridgeScope: "model" },
	"export_html": { lane: "ordered", bridgeScope: "export" },
	"follow_up": { lane: "ordered", bridgeScope: "prompt" },
	"get_available_models": { lane: "fast_lane_safe_read", bridgeScope: "model" },
	"get_branch_messages": { lane: "fast_lane_safe_read", bridgeScope: "session" },
	"get_last_assistant_text": { lane: "fast_lane_safe_read", bridgeScope: "message:read" },
	"get_login_providers": { lane: "fast_lane_safe_read", bridgeScope: "admin" },
	"get_messages": { lane: "fast_lane_safe_read", bridgeScope: "message:read" },
	"get_pending_workflow_gates": { lane: "fast_lane_safe_read", bridgeScope: "message:read" },
	"get_session_stats": { lane: "fast_lane_safe_read", bridgeScope: "message:read" },
	"get_state": { lane: "fast_lane_safe_read", bridgeScope: "message:read" },
	"handoff": { lane: "ordered", bridgeScope: "admin" },
	"login": { lane: "ordered", bridgeScope: "admin" },
	"negotiate_unattended": { lane: "ordered", bridgeScope: "control" },
	"new_session": { lane: "ordered", bridgeScope: "session" },
	"prompt": { lane: "ordered", bridgeScope: "prompt" },
	"set_auto_compaction": { lane: "ordered", bridgeScope: "control" },
	"set_auto_retry": { lane: "ordered", bridgeScope: "control" },
	"set_follow_up_mode": { lane: "ordered", bridgeScope: "control" },
	"set_host_tools": { lane: "ordered", bridgeScope: "host_tools" },
	"set_host_uri_schemes": { lane: "ordered", bridgeScope: "host_uri" },
	"set_interrupt_mode": { lane: "ordered", bridgeScope: "control" },
	"set_model": { lane: "ordered", bridgeScope: "model" },
	"set_session_name": { lane: "ordered", bridgeScope: "session" },
	"set_steering_mode": { lane: "ordered", bridgeScope: "control" },
	"set_thinking_level": { lane: "ordered", bridgeScope: "model" },
	"set_todos": { lane: "ordered", bridgeScope: "control" },
	"steer": { lane: "ordered", bridgeScope: "prompt" },
	"switch_session": { lane: "ordered", bridgeScope: "session" },
	"workflow_gate_response": { lane: "ordered", bridgeScope: "prompt" },
} as const satisfies Record<Command, { lane: SchedulingLane; bridgeScope: string }>;

export type CommandClass = { [K in Command]: { command: K; lane: (typeof COMMAND_CLASSIFICATION)[K]["lane"]; bridgeScope: (typeof COMMAND_CLASSIFICATION)[K]["bridgeScope"] } }[Command];

export const CAPABILITY_SCOPES = [
	"subscribe",
	"read",
	"control",
	"gate_answer",
	"host_tool_result",
	"host_uri_result",
	"host_tool_register",
	"host_uri_register",
	"enumerate",
	"admin",
] as const;
export type CapabilityScope = (typeof CAPABILITY_SCOPES)[number];

export const REDACTION_POLICIES = ["full", "redacted", "metadata_only"] as const;
export type RedactionPolicy = (typeof REDACTION_POLICIES)[number];
