import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface InventorySection { name: string; items: string[]; count: number; source: string; derivedAtRuntime: boolean }
interface Inventory { schemaVersion: number; kind: string; protocolVersion: number; sections: InventorySection[]; totalItems: number }
interface CommandEntry { command: string; bridgeScope: string; lane: string }
interface CommandManifest { schemaVersion: number; kind: string; commandCount: number; commands: CommandEntry[]; unclassified: string[] }

const root = resolve(import.meta.dir, "../..");
const inventoryPath = resolve(root, "docs/rpc-sdk/runtime-io-inventory.json");
const manifestPath = resolve(root, "docs/rpc-sdk/command-classification-manifest.json");
const outPath = resolve(root, "packages/rpc-sdk/src/protocol/generated.ts");
const inventory = JSON.parse(readFileSync(inventoryPath, "utf8")) as Inventory;
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as CommandManifest;

const pascal = (name: string) => name.split("_").map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
const quote = (value: string) => JSON.stringify(value);
const typeNames: Record<string, string> = { COMMANDS: "Command", AGENT_EVENTS: "AgentEvent", FRAME_TYPES: "InventoryFrameType", NOTIFICATION_SERVER_MESSAGES: "NotificationServerMessage", NOTIFICATION_CLIENT_MESSAGES: "NotificationClientMessage" };
const arrayConst = (name: string, values: string[]) => `export const ${name} = [\n${values.map((v) => `\t${quote(v)},`).join("\n")}\n] as const;\nexport type ${typeNames[name] ?? name.replace(/S$/, "")} = (typeof ${name})[number];`;
const section = (name: string): InventorySection => {
	const found = inventory.sections.find((s) => s.name === name);
	if (!found) throw new Error(`Missing inventory section ${name}`);
	return found;
};
const commandObjects = manifest.commands.map((entry) => `\t${quote(entry.command)}: { lane: ${quote(entry.lane)}, bridgeScope: ${quote(entry.bridgeScope)} },`).join("\n");
const body = `// Generated by scripts/rpc-sdk/generate-rpc-sdk-types.ts. Do not edit by hand.\n\nexport const PROTOCOL_VERSION = ${inventory.protocolVersion} as const;\nexport const INVENTORY_SCHEMA_VERSION = ${inventory.schemaVersion} as const;\nexport const INVENTORY_KIND = ${quote(inventory.kind)} as const;\nexport const INVENTORY_TOTAL_ITEMS = ${inventory.totalItems} as const;\n\n${arrayConst("COMMANDS", section("commands").items)}\n\n${arrayConst("AGENT_EVENTS", section("agent_events").items)}\n\n${arrayConst("FRAME_TYPES", section("frame_types").items)}\n\n${arrayConst("NOTIFICATION_SERVER_MESSAGES", section("notification_server_messages").items)}\n\n${arrayConst("NOTIFICATION_CLIENT_MESSAGES", section("notification_client_messages").items)}\n\nexport const SCHEDULING_LANES = [\n\t"fast_lane_cancellation",\n\t"fast_lane_safe_read",\n\t"ordered",\n] as const;\nexport type SchedulingLane = (typeof SCHEDULING_LANES)[number];\n\nexport const COMMAND_CLASSIFICATION = {\n${commandObjects}\n} as const satisfies Record<Command, { lane: SchedulingLane; bridgeScope: string }>;\n\nexport type CommandClass = { [K in Command]: { command: K; lane: (typeof COMMAND_CLASSIFICATION)[K]["lane"]; bridgeScope: (typeof COMMAND_CLASSIFICATION)[K]["bridgeScope"] } }[Command];\n\nexport const CAPABILITY_SCOPES = [\n\t"subscribe",\n\t"read",\n\t"control",\n\t"gate_answer",\n\t"host_tool_result",\n\t"host_uri_result",\n\t"host_tool_register",\n\t"host_uri_register",\n\t"enumerate",\n\t"admin",\n] as const;\nexport type CapabilityScope = (typeof CAPABILITY_SCOPES)[number];\n\nexport const REDACTION_POLICIES = ["full", "redacted", "metadata_only"] as const;\nexport type RedactionPolicy = (typeof REDACTION_POLICIES)[number];\n`;

if (process.argv.includes("--check")) {
	const current = readFileSync(outPath, "utf8");
	if (current !== body) {
		throw new Error(`${outPath} is stale; run bun scripts/rpc-sdk/generate-rpc-sdk-types.ts`);
	}
} else {
	writeFileSync(outPath, body);
}
