import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface InventorySection {
	name: string;
	source: string;
	derivedAtRuntime: boolean;
	count: number;
	items: string[];
}

interface RuntimeIoInventory {
	schemaVersion: number;
	kind: string;
	protocolVersion: number;
	sections: InventorySection[];
	totalItems: number;
}

const root = resolve(import.meta.dir, "../..");
const inventoryPath = resolve(root, "docs/rpc-sdk/runtime-io-inventory.json");
const outPath = resolve(root, "crates/gjc-rpc-sdk/tests/generated/runtime_io_conformance.rs");

function quoteRust(value: string): string {
	return JSON.stringify(value);
}

function validate(inv: RuntimeIoInventory): void {
	if (inv.schemaVersion !== 1) throw new Error(`unsupported inventory schemaVersion ${inv.schemaVersion}`);
	if (inv.kind !== "rpc-sdk-runtime-io-inventory") throw new Error(`unexpected inventory kind ${inv.kind}`);
	const seen = new Set<string>();
	let total = 0;
	for (const section of inv.sections) {
		if (section.count !== section.items.length) {
			throw new Error(`section ${section.name} count=${section.count} but has ${section.items.length} items`);
		}
		for (const item of section.items) {
			const key = `${section.name}:${item}`;
			if (seen.has(key)) throw new Error(`duplicate inventory item ${key}`);
			seen.add(key);
		}
		total += section.items.length;
	}
	if (total !== inv.totalItems) throw new Error(`totalItems=${inv.totalItems} but sections contain ${total}`);
}

function render(inv: RuntimeIoInventory): string {
	let ordinal = 0;
	const fixtures = inv.sections.flatMap((section) =>
		section.items.map((item) => {
			const line = `\tRuntimeIoFixture { section: ${quoteRust(section.name)}, item: ${quoteRust(item)}, ordinal: ${ordinal} },`;
			ordinal += 1;
			return line;
		}),
	);
	return `// Generated by scripts/rpc-sdk/generate-runtime-io-conformance.ts. Do not edit by hand.\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\npub struct RuntimeIoFixture {\n\tpub section: &'static str,\n\tpub item: &'static str,\n\tpub ordinal: usize,\n}\n\npub const INVENTORY_SCHEMA_VERSION: u32 = ${inv.schemaVersion};\npub const INVENTORY_KIND: &str = ${quoteRust(inv.kind)};\npub const INVENTORY_PROTOCOL_VERSION: u32 = ${inv.protocolVersion};\npub const INVENTORY_SECTION_COUNT: usize = ${inv.sections.length};\npub const INVENTORY_TOTAL_ITEMS: usize = ${inv.totalItems};\n\npub const RUNTIME_IO_FIXTURES: &[RuntimeIoFixture] = &[\n${fixtures.join("\n")}\n];\n`;
}

function main(): void {
	const inv = JSON.parse(readFileSync(inventoryPath, "utf8")) as RuntimeIoInventory;
	validate(inv);
	const next = render(inv);
	if (process.argv.includes("--check")) {
		let current = "";
		try {
			current = readFileSync(outPath, "utf8");
		} catch {
			console.error(`FAIL: conformance fixtures missing at ${outPath}; run without --check to generate.`);
			process.exit(1);
		}
		if (current !== next) {
			console.error("FAIL: runtime_io_conformance generated fixtures are stale; regenerate.");
			process.exit(1);
		}
		console.log(`OK: runtime_io_conformance in sync (${inv.totalItems} fixtures across ${inv.sections.length} sections)`);
		return;
	}
	mkdirSync(resolve(outPath, ".."), { recursive: true });
	writeFileSync(outPath, next);
	console.log(`OK: wrote ${inv.totalItems} conformance fixtures across ${inv.sections.length} sections to crates/gjc-rpc-sdk/tests/generated/runtime_io_conformance.rs`);
}

main();
