#!/usr/bin/env bun
import * as fs from "node:fs/promises";
import * as path from "node:path";

type Consumer = {
	path: string;
	symbols: string;
	specifier: string;
	usage: "type" | "value" | "mixed";
	replacement: string;
	status: "migrated" | "unmigrated";
};

const repoRoot = path.resolve(import.meta.dir, "..");
const outputPath = path.join(repoRoot, "docs/architecture/coding-agent-export-compatibility.md");
const roots = ["packages", "scripts", "docs", "examples", "bin"];

async function codingAgentConsumerPackageRoots(): Promise<string[]> {
	const packagesRoot = path.join(repoRoot, "packages");
	const roots: string[] = [];
	for (const entry of await fs.readdir(packagesRoot, { withFileTypes: true })) {
		if (!entry.isDirectory()) continue;
		const manifestPath = path.join(packagesRoot, entry.name, "package.json");
		try {
			const manifest = (await Bun.file(manifestPath).json()) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
			if (manifest.dependencies?.["@gajae-code/coding-agent"] || manifest.devDependencies?.["@gajae-code/coding-agent"]) roots.push(`packages/${entry.name}`);
		} catch {
			continue;
		}
	}
	return roots.sort();
}
const ignored = ["node_modules/", ".git/", "dist/", "coverage/", ".generated.", ".generated/"];
const extensions = new Set([".ts", ".tsx", ".mts", ".js", ".mjs", ".md"]);
const imports = /\b(import|export)\s+(type\s+)?(?:[^;"']*?\s+from\s+)?["'](@gajae-code\/coding-agent(?:\/[A-Za-z0-9_./-]+)?)["']/g;

function symbols(statement: string): string {
	const named = statement.match(/\{([\s\S]*?)\}/)?.[1];
	if (named) return named.replace(/\s+/g, " ").trim();
	if (/\*\s+as\s+/.test(statement)) return "*";
	return "default";
}

function render(consumers: Consumer[]): string {
	const rows = consumers.map(consumer =>
		`| \`${consumer.path}\` | \`${consumer.symbols}\` | \`${consumer.specifier}\` | ${consumer.usage} | \`${consumer.replacement}\` | ${consumer.status} | ${consumer.specifier === "@gajae-code/coding-agent" || consumer.specifier === "@gajae-code/coding-agent/sdk" || consumer.specifier === "@gajae-code/coding-agent/cli" ? "retained" : "removed"} |`,
	);
	return `# Coding-agent export compatibility\n\nGenerated by \`bun scripts/inventory-coding-agent-exports.ts\`; do not edit manually. The stable surface is package root (SDK factories/types and extension contracts), \`./sdk\`, and \`./cli\`. All topology-derived deep exports are removed.\n\n| Consumer | Symbols | Old import | Type/value | Replacement | Status | Final decision |\n| --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\nConsumer count: ${consumers.length}. Unmigrated: ${consumers.filter(consumer => consumer.status === "unmigrated").length}.\n`;
}

const consumers: Consumer[] = [];
for (const root of roots) {
	const absoluteRoot = path.join(repoRoot, root);
	try {
		if (!(await fs.stat(absoluteRoot)).isDirectory()) continue;
	} catch {
		continue;
	}
	const glob = new Bun.Glob("**/*");
	for await (const relative of glob.scan({ cwd: absoluteRoot, onlyFiles: true })) {
		const file = path.join(absoluteRoot, relative);
		const repoPath = path.relative(repoRoot, file).replaceAll(path.sep, "/");
		if (ignored.some(part => repoPath.includes(part)) || !extensions.has(path.extname(file))) continue;
		if (repoPath.startsWith("packages/coding-agent/src/")) continue;
		const source = await Bun.file(file).text();
		for (const match of source.matchAll(imports)) {
			const statement = match[0];
			const specifier = match[3];
			const usage = match[2] ? "type" : statement.includes("import type") ? "type" : "value";
			const retained = specifier === "@gajae-code/coding-agent" || specifier === "@gajae-code/coding-agent/sdk" || specifier === "@gajae-code/coding-agent/cli";
			const negativeCompatibilityCase = repoPath === "packages/coding-agent/test/export-map-compatibility.test.ts" && !retained;
			consumers.push({
				path: repoPath,
				symbols: symbols(statement),
				specifier,
				usage,
				replacement: retained ? specifier : negativeCompatibilityCase ? "negative resolution assertion" : "relative internal module",
				status: retained || negativeCompatibilityCase ? "migrated" : "unmigrated",
			});
		}
	}
}
const expectedConsumerRoots = await codingAgentConsumerPackageRoots();
const missingConsumerRoots = expectedConsumerRoots.filter(root => !consumers.some(consumer => consumer.path.startsWith(`${root}/`)));
if (missingConsumerRoots.length > 0) throw new Error(`coding-agent dependency packages missing from inventory: ${missingConsumerRoots.join(", ")}`);
consumers.sort((a, b) => `${a.path}\0${a.specifier}\0${a.symbols}`.localeCompare(`${b.path}\0${b.specifier}\0${b.symbols}`));
const document = render(consumers);
const check = process.argv.includes("--check");
if (check) {
	const current = (await Bun.file(outputPath).exists()) ? await Bun.file(outputPath).text() : "";
	if (current !== document || consumers.some(consumer => consumer.status === "unmigrated")) {
		throw new Error(`coding-agent export inventory is stale or has unmigrated consumers (${consumers.filter(consumer => consumer.status === "unmigrated").length})`);
	}
} else {
	await Bun.write(outputPath, document);
}
