#!/usr/bin/env bun
/** Offline deterministic cross-layer ralplan IRC acceptance gate. */
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type { ImageContent, TextContent } from "@gajae-code/ai";
import { Agent } from "@gajae-code/agent-core";
import { Settings } from "../packages/coding-agent/src/config/settings";
import { adaptTaskTokenLogsToRalplanCacheTurns, compareRalplanCacheTurns, renderRalplanCacheEvidenceForAdr, type RalplanCacheMode, type RalplanCacheTurn, type RalplanCacheTurnKey } from "../packages/coding-agent/src/gjc-runtime/ralplan-cache-comparison";
import { RalplanIrcCoordinator, type RalplanIrcPassState } from "../packages/coding-agent/src/gjc-runtime/ralplan-irc-coordinator";
import { degradeRalplanIrcPass, runNativeRalplanCommand } from "../packages/coding-agent/src/gjc-runtime/ralplan-runtime";
import { AgentRegistry } from "../packages/coding-agent/src/registry/agent-registry";
import { AgentSession } from "../packages/coding-agent/src/session/agent-session";
import { SessionManager } from "../packages/coding-agent/src/session/session-manager";
import type { TaskTokenLog } from "../packages/coding-agent/src/task/types";
import type { ToolSession } from "../packages/coding-agent/src/tools";
import { IrcTool } from "../packages/coding-agent/src/tools/irc";

type Scenario = "happy-path" | "three-peer-critic-dm-planner" | "degrade-matrix" | "cache-comparison" | "legacy-regression";
type Fake = { session: AgentSession; calls: string[]; fail?: Error; hold?: boolean; holdBeforeDelivery?: boolean };
type OpenRun = { runId: string; registry: AgentRegistry; coordinator: RalplanIrcCoordinator; main: IrcTool; planner: IrcTool; critic: IrcTool; plannerFake: Fake; cursor: { runId: string; stageN: number; cursorGeneration: number }; dispose: () => Promise<void> };
const scenarios = new Set<Scenario>(["happy-path", "three-peer-critic-dm-planner", "degrade-matrix", "cache-comparison", "legacy-regression"]);

function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
async function scratch(): Promise<string> { return await fs.mkdtemp(path.join(os.tmpdir(), "gjc-irc-consensus-")); }
async function withScratch(action: (cwd: string) => Promise<void>): Promise<void> { const cwd = await scratch(); try { await action(cwd); } finally { await fs.chmod(path.join(cwd, ".gjc"), 0o700).catch(() => {}); await fs.rm(cwd, { recursive: true, force: true }); } }
async function seed(cwd: string, sessionId = "parent"): Promise<string> { const result = await runNativeRalplanCommand(["--irc", "--json", "--session-id", sessionId, "offline verification"], cwd); assert(result.status === 0 && result.stdout, `failed to seed IRC run: ${result.stderr ?? "no receipt"}`); return (JSON.parse(result.stdout) as { run_id: string }).run_id; }
type BackgroundResponseArgs = Parameters<AgentSession["respondAsBackground"]>[0];
function fake(agentId: string, registry: AgentRegistry): Fake { const result: Fake = { calls: [], session: realSession(agentId, registry) }; result.session.respondAsBackground = async (args: BackgroundResponseArgs) => { result.calls.push(args.message); if (result.fail) throw result.fail; if (result.holdBeforeDelivery) await new Promise<void>(() => {}); args.onDelivered?.(); if (result.hold) await new Promise<void>(() => {}); return { replyText: args.awaitReply === false ? null : "ack" }; }; return result; }
function realSession(agentId: string, registry: AgentRegistry): AgentSession { return new AgentSession({ agent: new Agent({ initialState: { systemPrompt: ["system prompt"], messages: [], tools: [] } }), sessionManager: SessionManager.inMemory(), settings: Settings.isolated({ "compaction.enabled": false }), modelRegistry: {} as never, agentId, agentRegistry: registry }); }
function toolSession(registry: AgentRegistry, cwd: string, id: string, sessionId: string): ToolSession { return { cwd, hasUI: false, getSessionFile: () => null, getSessionSpawns: () => "*", settings: Settings.isolated(), agentRegistry: registry, getAgentId: () => id, getSessionId: () => sessionId }; }
function text(result: { content: Array<TextContent | ImageContent> }): string { return result.content.filter((value): value is TextContent => value.type === "text").map(value => value.text).join("\n"); }
function state(coordinator: RalplanIrcCoordinator): RalplanIrcPassState { return coordinator.state; }
function attach(registry: AgentRegistry, coordinator: RalplanIrcCoordinator, id: string, role: "planner" | "architect" | "critic", runId: string, session = fake(id, registry)): Fake { const registered = registry.register({ id, displayName: role, kind: "sub", parentId: "0-Main", session: null }); assert(coordinator.bindRegisteredChild(id, { parentSessionId: "parent", runId, role, token: registered.token }), `could not bind ${role}`); registry.attachSession(id, session.session, undefined, { token: registered.token }); return session; }
function attachSession(registry: AgentRegistry, coordinator: RalplanIrcCoordinator, id: string, role: "planner" | "architect" | "critic", runId: string, session: AgentSession): void { const registered = registry.register({ id, displayName: role, kind: "sub", parentId: "0-Main", session: null }); assert(coordinator.bindRegisteredChild(id, { parentSessionId: "parent", runId, role, token: registered.token }), `could not bind ${role}`); registry.attachSession(id, session, undefined, { token: registered.token }); }

async function openThreePeers(cwd: string, stageN = 1, relayThroughAgentSession = false): Promise<OpenRun> {
	const runId = await seed(cwd); const registry = new AgentRegistry(); const coordinator = new RalplanIrcCoordinator({ registry, cwd, sendTimeoutMs: 1 }); const sessions: AgentSession[] = [];
	const mainSession = relayThroughAgentSession ? realSession("0-Main", registry) : fake("0-Main", registry).session; if (relayThroughAgentSession) sessions.push(mainSession); registry.register({ id: "0-Main", displayName: "main", kind: "main", session: mainSession });
	const main = new IrcTool(toolSession(registry, cwd, "0-Main", "parent")); const cursor = { runId, stageN, cursorGeneration: 7 };
	assert(!text(await main.execute("start", { op: "ralplan_pass_start", ...cursor })).includes("No matching"), "IrcTool rejected authorized pass start");
	let plannerFake: Fake;
	if (relayThroughAgentSession) { const plannerSession = realSession("planner", registry); sessions.push(plannerSession); attachSession(registry, coordinator, "planner", "planner", runId, plannerSession); plannerFake = { calls: [], session: plannerSession }; } else plannerFake = attach(registry, coordinator, "planner", "planner", runId);
	attach(registry, coordinator, "architect", "architect", runId); attach(registry, coordinator, "critic", "critic", runId);
	return { runId, registry, coordinator, main, planner: new IrcTool(toolSession(registry, cwd, "planner", "planner")), critic: new IrcTool(toolSession(registry, cwd, "critic", "critic")), plannerFake, cursor, dispose: async () => { coordinator.close(); await Promise.all(sessions.map(session => session.dispose())); } };
}

async function threePeer(cwd: string): Promise<void> { const run = await openThreePeers(cwd); try { assert(state(run.coordinator) === "awaiting_required_dm", "attached sessions did not reach required-DM gate"); const architect = new IrcTool(toolSession(run.registry, cwd, "architect", "architect")); await architect.execute("architect", { op: "send", to: "planner", message: "review", awaitReply: false }); assert(state(run.coordinator) === "awaiting_required_dm", "Architect delivery opened deliberation"); const delivery = await run.critic.execute("critic", { op: "send", to: "planner", message: "independent review", awaitReply: false }); assert(delivery.details?.delivered?.includes("planner"), "IrcTool lacked delivery acknowledgement"); assert(state(run.coordinator) === "deliberation_open", "Critic delivery did not open deliberation"); } finally { await run.dispose(); } }

async function happyPath(): Promise<void> { await withScratch(async cwd => { await threePeer(cwd); const run = await openThreePeers(cwd, 2, true); try { await run.critic.execute("critic", { op: "send", to: "planner", message: "evidence", awaitReply: false }); const ended = await run.main.execute("end", { op: "ralplan_pass_end", ...run.cursor }); assert(text(ended).includes("evidence"), "AgentSession relay observation was not rendered"); const premature = await run.main.execute("receipt-before-write", { op: "ralplan_deliberation_receipt_recorded", ...run.cursor }); assert(text(premature).includes("No matching completed"), "boundary accepted before deliberation artifact write"); const receipt = await runNativeRalplanCommand(["--write", "--stage", "deliberation", "--stage_n", "2", "--run-id", run.runId, "--session-id", "parent", "--artifact", text(ended), "--json"], cwd); assert(receipt.status === 0, "deliberation write failed"); const boundary = await run.main.execute("receipt", { op: "ralplan_deliberation_receipt_recorded", ...run.cursor }); assert(text(boundary).includes("recorded"), "boundary was not accepted after deliberation artifact write"); } finally { await run.dispose(); } }); }

async function degradeMatrix(): Promise<void> { await withScratch(async cwd => { for (const reason of ["resume_failed", "deliberation_write_failed", "delivery_failed", "send_timeout"] as const) { const scenarioCwd = path.join(cwd, reason); await fs.mkdir(scenarioCwd); const run = await openThreePeers(scenarioCwd); if (reason === "resume_failed") { const staleRegistration = run.registry.register({ id: "bad", displayName: "bad", kind: "sub", session: fake("bad", run.registry).session }); run.registry.unregister("bad", staleRegistration.token); run.registry.register({ id: "bad", displayName: "bad", kind: "sub", session: fake("bad", run.registry).session }); assert(!run.coordinator.bindRegisteredChild("bad", { parentSessionId: "parent", runId: run.runId, role: "planner", token: staleRegistration.token }), "binding rejection was not exercised"); await run.main.execute("failure", { op: "ralplan_report_failure", ...run.cursor, reason }); } else if (reason === "deliberation_write_failed") { await run.critic.execute("critic", { op: "send", to: "planner", message: "review", awaitReply: false }); await run.main.execute("end", { op: "ralplan_pass_end", ...run.cursor }); const artifactRoot = path.join(scenarioCwd, ".gjc", "_session-parent", "plans"); await fs.rm(artifactRoot, { recursive: true, force: true }); await fs.writeFile(artifactRoot, "unwritable artifact root"); const write = await runNativeRalplanCommand(["--write", "--stage", "deliberation", "--stage_n", "1", "--run-id", run.runId, "--session-id", "parent", "--artifact", "receipt"], scenarioCwd); assert(write.status !== 0, "unwritable deliberation path unexpectedly wrote"); await degradeRalplanIrcPass({ cwd: scenarioCwd, sessionId: "parent", runId: run.runId, stageN: run.cursor.stageN, reason }); } else { run.plannerFake.fail = reason === "delivery_failed" ? new Error("rejected") : undefined; if (reason === "send_timeout") run.plannerFake.holdBeforeDelivery = true; await run.critic.execute("send", { op: "send", to: "planner", message: "fails", awaitReply: false }); } assert(reason === "deliberation_write_failed" || state(run.coordinator) === "degraded", `${reason}: coordinator not degraded`); const persistedState = JSON.parse(await fs.readFile(path.join(scenarioCwd, ".gjc", "_session-parent", "state", "ralplan-state.json"), "utf8")) as { irc_degraded?: boolean; irc_degrade_reason?: string }; assert(persistedState.irc_degraded && persistedState.irc_degrade_reason === reason, `${reason}: durable latch/reason absent`); assert(text(await run.main.execute("later", { op: "ralplan_status", ...run.cursor })).includes("No matching"), `${reason}: later IRC operation accepted`); await run.dispose(); } }); }

function cacheTurns(unfavorable = false): RalplanCacheTurn[] { const turns: RalplanCacheTurn[] = []; for (const mode of ["irc", "legacy"] as const) { const entries = [["architect", "architect-1", 1], ["critic", "critic-1", 2], ["architect", "architect-2", 3]] as const; const logs: TaskTokenLog[] = entries.map(([agent, subagentId, turn]) => ({ subagentId, agent, turn, at: `2026-01-01T00:00:0${turn}.000Z`, input: 100, output: 20, cacheRead: mode === "irc" ? 50 : unfavorable ? 50 : 0, cacheWrite: 10, totalTokens: mode === "irc" || unfavorable ? 180 : 130, model: "test" })); const keys: RalplanCacheTurnKey[] = entries.map(([role, subagentId, turn]) => ({ runId: `${mode}-run`, mode: mode as RalplanCacheMode, role, subagentId, pass: 2, turn, provider: "offline", model: "test", attemptId: `${role}-${subagentId}-${turn}`, attemptOrdinal: turn })); turns.push(...adaptTaskTokenLogsToRalplanCacheTurns(logs, keys)); } return turns; }
async function cacheComparison(maxPairs: number, unfavorable: boolean): Promise<void> { await withScratch(async cwd => { const evidence = compareRalplanCacheTurns(cacheTurns(unfavorable), maxPairs); assert(evidence.comparisons.length === 3 && evidence.disqualifications.length === 0, "expected three measurable pairs"); assert(evidence.comparisons.every(pair => pair.ircCacheHitRate! > pair.legacyCacheHitRate!), "cache improvement is not measurable"); const artifact = path.join(cwd, "cache-evidence.md"); await fs.writeFile(artifact, renderRalplanCacheEvidenceForAdr(evidence)); const write = await runNativeRalplanCommand(["--write", "--stage", "adr", "--stage_n", "1", "--run-id", "cache-evidence", "--session-id", "cache", "--artifact", artifact, "--json"], cwd); assert(write.status === 0, `cache evidence write failed: ${write.stderr}`); }); if (!unfavorable) { const child = Bun.spawn([process.execPath, import.meta.path, "--scenario", "cache-comparison", "--max-pairs", String(maxPairs), "--unfavorable"], { stdout: "pipe", stderr: "pipe" }); assert(await child.exited !== 0, "unfavorable no-improvement invocation exited successfully"); } }
async function legacyRegression(): Promise<void> { await withScratch(async cwd => { const result = await runNativeRalplanCommand(["--json", "--session-id", "legacy", "offline verification"], cwd); assert(result.status === 0 && result.stdout, "legacy handoff failed"); const payload = JSON.parse(result.stdout) as { irc?: unknown; run_id?: unknown }; assert(!("irc" in payload) && typeof payload.run_id === "string", "legacy handoff changed receipt shape"); }); }
const requested = process.argv[process.argv.indexOf("--scenario") + 1] as Scenario | undefined; const maxIndex = process.argv.indexOf("--max-pairs"); const maxPairs = maxIndex >= 0 ? Number(process.argv[maxIndex + 1]) : 3; const unfavorable = process.argv.includes("--unfavorable");
if (!requested || !scenarios.has(requested) || !Number.isInteger(maxPairs) || maxPairs < 0) { console.error("Usage: bun scripts/verify-ralplan-irc-consensus.ts --scenario <happy-path|three-peer-critic-dm-planner|degrade-matrix|cache-comparison|legacy-regression> [--max-pairs 3] [--unfavorable]"); process.exit(2); }
try { if (requested === "happy-path") await happyPath(); else if (requested === "three-peer-critic-dm-planner") await withScratch(threePeer); else if (requested === "degrade-matrix") await degradeMatrix(); else if (requested === "cache-comparison") await cacheComparison(maxPairs, unfavorable); else await legacyRegression(); console.log(`PASS ${requested}`); } catch (error) { console.error(`FAIL ${requested}: ${error instanceof Error ? error.message : String(error)}`); process.exit(1); }
