import * as fs from "node:fs/promises";
import * as path from "node:path";
import { type BuildSidecar, type CandidateAddon, verifyDefaultLanguageSet } from "./embed-guard";

export type EmbeddedAddonVariant = CandidateAddon["variant"];

const validEmbedVariants = new Set<EmbeddedAddonVariant>(["modern", "baseline", "default"]);
const validEmbedTopologies = new Set(["monolith", "core"] as const);
type EmbedTopology = "monolith" | "core";
const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 */

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;

export function parseEmbedVariants(value: string | undefined): Set<EmbeddedAddonVariant> | null {
	if (!value) {
		return null;
	}

	const variants = value
		.split(",")
		.map(variant => variant.trim())
		.filter(Boolean);
	const unknownVariants = variants.filter(variant => !validEmbedVariants.has(variant as EmbeddedAddonVariant));
	if (unknownVariants.length > 0) {
		throw new Error(
			`Invalid EMBED_VARIANTS value(s): ${unknownVariants.join(", ")}. Valid values are: modern, baseline, default.`,
		);
	}

	return new Set(variants as EmbeddedAddonVariant[]);
}

export function buildCandidateList(
	targetArch: string,
	platformTag: string,
	topology: EmbedTopology = "monolith",
): CandidateAddon[] {
	const prefix = topology === "core" ? "pi_natives_core" : "pi_natives";
	return targetArch === "x64"
		? [
				{ variant: "modern", filename: `${prefix}.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `${prefix}.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `${prefix}.${platformTag}.node` }];
}

export function filterCandidatesByVariant(
	candidates: CandidateAddon[],
	requestedVariants: Set<EmbeddedAddonVariant> | null,
	platformTag: string,
): CandidateAddon[] {
	if (!requestedVariants) {
		return candidates;
	}

	const filtered = candidates.filter(candidate => requestedVariants.has(candidate.variant));
	if (filtered.length === 0) {
		throw new Error(
			`EMBED_VARIANTS selected no candidates for ${platformTag}. Requested: ${[...requestedVariants].join(", ")}; available variants for target: ${candidates.map(candidate => candidate.variant).join(", ")}.`,
		);
	}
	return filtered;
}

async function readBuildSidecar(candidatePath: string): Promise<BuildSidecar | null> {
	const sidecarPath = `${candidatePath}.build.json`;
	try {
		return (await Bun.file(sidecarPath).json()) as BuildSidecar;
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
		throw err;
	}
}

async function fileExists(filePath: string): Promise<boolean> {
	try {
		await fs.stat(filePath);
		return true;
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
		throw err;
	}
}

export function parseEmbedTopology(value: string | undefined): EmbedTopology {
	const topology = value || "monolith";
	if (!validEmbedTopologies.has(topology as EmbedTopology)) {
		throw new Error(`Invalid EMBED_TOPOLOGY value: ${topology}. Valid values are: monolith, core.`);
	}
	return topology as EmbedTopology;
}

async function embedNative(): Promise<void> {
	if (process.argv.includes("--reset")) {
		await Bun.write(outputPath, stubContent);
		return;
	}

	const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
	const targetArch = Bun.env.TARGET_ARCH || process.arch;
	const platformTag = `${targetPlatform}-${targetArch}`;
	const hostPlatformTag = `${process.platform}-${process.arch}`;
	const topology = parseEmbedTopology(Bun.env.EMBED_TOPOLOGY);
	const candidates = filterCandidatesByVariant(
		buildCandidateList(targetArch, platformTag, topology),
		parseEmbedVariants(Bun.env.EMBED_VARIANTS),
		platformTag,
	);

	const available: CandidateAddon[] = [];
	for (const candidate of candidates) {
		const candidatePath = path.join(nativeDir, candidate.filename);
		if (await fileExists(candidatePath)) {
			await verifyDefaultLanguageSet(candidate, candidatePath, {
				platformTag,
				hostPlatformTag,
				readBuildSidecar,
				loadNativeAddon: candidatePath =>
					require(candidatePath) as { nativeBuildInfo?: () => { languageSet?: string } },
				warn: message => console.warn(message),
			});
			available.push(candidate);
		}
	}

	if (available.length === 0) {
		const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
		throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
	}
	const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };

	const imports = available
		.map(
			(candidate, index) =>
				`import addonPath${index} from ${JSON.stringify(`../native/${candidate.filename}`)} with { type: "file" };`,
		)
		.join("\n");

	const files = available
		.map(
			(candidate, index) =>
				`\t\t{ variant: ${JSON.stringify(candidate.variant)}, filename: ${JSON.stringify(candidate.filename)}, filePath: addonPath${index} },`,
		)
		.join("\n");

	const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {"monolith" | "core"} topology
 * @property {EmbeddedAddonFile[]} files
 */

${imports}

export const embeddedAddon = {
	platformTag: ${JSON.stringify(platformTag)},
	version: ${JSON.stringify(packageJson.version)},
	topology: ${JSON.stringify(topology)},
	files: [
${files}
	],
};
`;

	await Bun.write(outputPath, content);
}

if (import.meta.main) {
	await embedNative();
}
